server:
  compression:
    enabled: true
    min-response-size: 1
  connection-timeout: 5000
  port: 8080
  session:
    timeout: 5

spring:
  session:
    store-type: redis
  redis:
    host: 172.168.1.106
    port: 6379
    password: 123456
  datasource:
    name: test
    url: jdbc:mysql://172.168.1.106:3306/test
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#security:
#  oauth2:
#    client:
#      client-id: testclient
#      client-secret: testsecret
#      scope: read,write
#      auto-approve-scopes: '.*'

app:
  name: Pabao
  wechat:
    enabled: true
    appid: wx50af58bedf7b620c
    secret: 9d9b9af72afa17abce68c96b4055768d